[server]
headless = true
enableStaticServing = true
enableXsrfProtection = true
enableCORS = true
maxUploadSize = 10
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#27634D"
backgroundColor = "#FAF8F2"
secondaryBackgroundColor = "#ECEEE4"
textColor = "#20382E"
borderColor = "#CCD4C8"
font = "sans-serif"
headingFont = "serif"
baseFontSize = 16
baseRadius = "large"
buttonRadius = "full"
showWidgetBorder = true
headingFontSizes = ["36px", "28px", "22px", "20px", "18px", "16px"]
chartCategoricalColors = ["#27634D", "#987547", "#61768A", "#8B627C"]
